ass4: PriorityQueue.o Call.o CallCenter.o Main.o

	g++ PriorityQueue.o Call.o CallCenter.o Main.o   -o ass4

PriorityQueue.o: PriorityQueue.cpp

			g++ -c -std=c++11 PriorityQueue.cpp
Call.o: Call.cpp

	g++ -c -std=c++11 Call.cpp

CallCenter.o: CallCenter.cpp

	g++ -c -std=c++11 CallCenter.cpp
Main.o: Main.cpp

		g++ -c -std=c++11 Main.cpp
CallTester.o: CallTester.cpp

		g++ -c -std=c++11 CallTester.cpp
