poker: poker.o main.o

	gcc poker.o main.o -o poker

main.o: main.c

	gcc -c -std=c++11 main.cpp

poker.o: poker.cpp

	gcc -c -std=c++11 ShoppingCart.cpp


ItemToPurchase.o: ItemToPurchase.cpp

	g++ -c -std=c++11 ItemToPurchase.cpp



LinkedList.o: LinkedList.cpp

	g++ -c -std=c++11 LinkedList.cpp
